#!/bin/bash
sleep 2;./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh r 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l ;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh r;sleep 1;
./win.sh l 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l ;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
./win.sh l 5;sleep 1;
./win.sh r;sleep 1;
./win.sh r 5;sleep 1;
./win.sh r;sleep 1;
./win.sh l 5;sleep 1;
./win.sh l;sleep 1;
./win.sh l 5;sleep 1;
